export type Mode = {
  key: string;
  label: string;
  shortLabel: string;
  badge: string;
  icon: string;
  href: string;
  description: string;
  accent: string;
  template: "image" | "quote" | "audio" | "logic" | "rebus" | "colors" | "word";
};

export const MODES: Mode[] = [
  {
    key: "game",
    label: "Guess The Game",
    shortLabel: "Game",
    badge: "VG",
    icon: "🎮",
    href: "/game",
    description: "Peel back six visual clues and name today's video game.",
    accent: "violet",
    template: "image",
  },
  {
    key: "book",
    label: "Guess The Book",
    shortLabel: "Book",
    badge: "BK",
    icon: "📖",
    href: "/book",
    description: "Try to guess today's book in 6 guesses or less using covers, scenes, and story clues.",
    accent: "emerald",
    template: "quote",
  },
  {
    key: "movie",
    label: "Guess The Movie",
    shortLabel: "Movie",
    badge: "MV",
    icon: "🎬",
    href: "/movie",
    description: "Frames, props, and posters from today's hidden film.",
    accent: "rose",
    template: "image",
  },
  {
    key: "logo",
    label: "Guess The Logo",
    shortLabel: "Logo",
    badge: "LG",
    icon: "⭐",
    href: "/logo",
    description: "Brand marks revealed from tight crops to full clarity.",
    accent: "amber",
    template: "image",
  },
  {
    key: "house",
    label: "Guess The House",
    shortLabel: "House",
    badge: "HS",
    icon: "🏠",
    href: "/house",
    description: "Architecture and interiors from memorable homes and landmarks.",
    accent: "indigo",
    template: "image",
  },
  {
    key: "angle",
    label: "Guess The Angle",
    shortLabel: "Angle",
    badge: "AG",
    icon: "📐",
    href: "/angle",
    description: "Extreme close-ups and strange perspectives that reward observation.",
    accent: "teal",
    template: "image",
  },
  {
    key: "phrase",
    label: "Guess The Phrase",
    shortLabel: "Phrase",
    badge: "PH",
    icon: "💬",
    href: "/phrase",
    description: "Visual riddles and rebus puzzles turned into a daily challenge.",
    accent: "pink",
    template: "rebus",
  },
  {
    key: "song",
    label: "Guess The Song",
    shortLabel: "Song",
    badge: "SG",
    icon: "🎵",
    href: "/song",
    description: "Album art, lyric fragments, and music video clues for one track.",
    accent: "purple",
    template: "audio",
  },
  {
    key: "animal",
    label: "Guess The Animal",
    shortLabel: "Animal",
    badge: "AN",
    icon: "🐾",
    href: "/animal",
    description: "Silhouettes, textures, and habitats that point to one animal.",
    accent: "orange",
    template: "image",
  },
  {
    key: "plant",
    label: "Guess The Plant",
    shortLabel: "Plant",
    badge: "PL",
    icon: "🌿",
    href: "/plant",
    description: "Leaves, flowers, and stems that reveal a single plant.",
    accent: "green",
    template: "image",
  },
  {
    key: "number",
    label: "Guess The Number",
    shortLabel: "Number",
    badge: "NM",
    icon: "123",
    href: "/number",
    description: "Logic-driven rounds where each clue tightens the answer.",
    accent: "blue",
    template: "logic",
  },
  {
    key: "price",
    label: "Guess The Price",
    shortLabel: "Price",
    badge: "PR",
    icon: "🏷️",
    href: "/price",
    description: "Estimate the mystery price using visuals and a limited reveal budget.",
    accent: "yellow",
    template: "logic",
  },
  {
    key: "colors",
    label: "Guess The Colors",
    shortLabel: "Colors",
    badge: "CL",
    icon: "🎨",
    href: "/colors",
    description: "Find the hidden color order using position feedback after each guess.",
    accent: "rainbow",
    template: "colors",
  },
  {
    key: "country",
    label: "Guess The Country",
    shortLabel: "Country",
    badge: "CY",
    icon: "🌐",
    href: "/country",
    description: "Identify a country from a blurred outline and geography clues.",
    accent: "violet",
    template: "image",
  },
  {
    key: "drawing",
    label: "Guess The Drawing",
    shortLabel: "Drawing",
    badge: "DR",
    icon: "✏️",
    href: "/drawing",
    description: "A sketch sharpens over time. Guess what is being drawn.",
    accent: "indigo",
    template: "image",
  },
  {
    key: "emoji",
    label: "Guess The Emoji",
    shortLabel: "Emoji",
    badge: "EJ",
    icon: "🙂",
    href: "/emoji",
    description: "Decode the emoji clue and submit the hidden phrase.",
    accent: "pink",
    template: "rebus",
  },
  {
    key: "flag",
    label: "Guess The Flag",
    shortLabel: "Flag",
    badge: "FL",
    icon: "🚩",
    href: "/flag",
    description: "Name the country from its flag and unlocked context clues.",
    accent: "blue",
    template: "image",
  },
  {
    key: "word",
    label: "Guess The Word",
    shortLabel: "Word",
    badge: "WD",
    icon: "W",
    href: "/word",
    description: "Solve the six-letter word from tile feedback and word hints.",
    accent: "violet",
    template: "word",
  },
];

export function getModeBadge(modeKey: string): string {
  return MODES.find((mode) => mode.key === modeKey)?.badge ?? "GT";
}

export function getModeIcon(modeKey: string): string {
  return MODES.find((mode) => mode.key === modeKey)?.icon ?? getModeBadge(modeKey);
}
